<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260318045417 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE board DROP CONSTRAINT board_owner_id_fkey');
        $this->addSql('ALTER TABLE board ADD uuid VARCHAR(36) DEFAULT NULL');
        $this->addSql('UPDATE board SET uuid = gen_random_uuid()::varchar WHERE uuid IS NULL');
        $this->addSql('ALTER TABLE board ALTER COLUMN uuid SET NOT NULL');
        $this->addSql('ALTER TABLE board ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE board ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE board ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE board ADD CONSTRAINT FK_58562B477E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_58562B47D17F50A6 ON board (uuid)');
        $this->addSql('ALTER INDEX idx_board_owner RENAME TO IDX_58562B477E3C61F9');
        $this->addSql('ALTER TABLE board_column DROP CONSTRAINT board_column_board_id_fkey');
        $this->addSql('ALTER TABLE board_column ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE board_column ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE board_column ADD CONSTRAINT FK_D14DC3D9E7EC5785 FOREIGN KEY (board_id) REFERENCES board (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_column_board RENAME TO IDX_D14DC3D9E7EC5785');
        $this->addSql('ALTER TABLE card DROP CONSTRAINT card_board_column_id_fkey');
        $this->addSql('ALTER TABLE card ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE card ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE card ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE card ADD CONSTRAINT FK_161498D3CA372FE FOREIGN KEY (board_column_id) REFERENCES board_column (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_card_column RENAME TO IDX_161498D3CA372FE');
        $this->addSql('ALTER TABLE "user" ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER roles DROP DEFAULT');
        $this->addSql('ALTER INDEX uniq_user_email RENAME TO UNIQ_8D93D649E7927C74');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE board DROP CONSTRAINT FK_58562B477E3C61F9');
        $this->addSql('DROP INDEX UNIQ_58562B47D17F50A6');
        $this->addSql('ALTER TABLE board DROP uuid');
        $this->addSql('ALTER TABLE board ALTER id SET DEFAULT nextval(\'board_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE board ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE board ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE board ADD CONSTRAINT board_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_58562b477e3c61f9 RENAME TO idx_board_owner');
        $this->addSql('ALTER TABLE board_column DROP CONSTRAINT FK_D14DC3D9E7EC5785');
        $this->addSql('ALTER TABLE board_column ALTER id SET DEFAULT nextval(\'board_column_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE board_column ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE board_column ADD CONSTRAINT board_column_board_id_fkey FOREIGN KEY (board_id) REFERENCES board (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_d14dc3d9e7ec5785 RENAME TO idx_column_board');
        $this->addSql('ALTER TABLE card DROP CONSTRAINT FK_161498D3CA372FE');
        $this->addSql('ALTER TABLE card ALTER id SET DEFAULT nextval(\'card_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE card ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE card ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE card ADD CONSTRAINT card_board_column_id_fkey FOREIGN KEY (board_column_id) REFERENCES board_column (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_161498d3ca372fe RENAME TO idx_card_column');
        $this->addSql('ALTER TABLE "user" ALTER id SET DEFAULT nextval(\'user_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE "user" ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER roles SET DEFAULT \'[]\'');
        $this->addSql('ALTER INDEX uniq_8d93d649e7927c74 RENAME TO uniq_user_email');
    }
}
